// 3dnow.h
// Copyright (c) 2020, zhiayang
// Licensed under the Apache License Version 2.0.

#pragma once

#include "entry.h"

namespace instrad::x64::tables
{
	constexpr TableEntry SecondaryOpcodeMap_0F_0F_3DNow[] = {
		/*00*/ entry_blank,
		/*01*/ entry_blank,
		/*02*/ entry_blank,
		/*03*/ entry_blank,
		/*04*/ entry_blank,
		/*05*/ entry_blank,
		/*06*/ entry_blank,
		/*07*/ entry_blank,

		/*08*/ entry_blank,
		/*09*/ entry_blank,
		/*0A*/ entry_blank,
		/*0B*/ entry_blank,
		/*0C*/ entry_2(0x0C, ops::PI2FW, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*0D*/ entry_2(0x0D, ops::PI2FD, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*0E*/ entry_blank,
		/*0F*/ entry_blank,

		/*10*/ entry_blank,
		/*11*/ entry_blank,
		/*12*/ entry_blank,
		/*13*/ entry_blank,
		/*14*/ entry_blank,
		/*15*/ entry_blank,
		/*16*/ entry_blank,
		/*17*/ entry_blank,

		/*18*/ entry_blank,
		/*19*/ entry_blank,
		/*1A*/ entry_blank,
		/*1B*/ entry_blank,
		/*1C*/ entry_2(0x1C, ops::PF2IW, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*1D*/ entry_2(0x1D, ops::PF2ID, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*1E*/ entry_blank,
		/*1F*/ entry_blank,

		/*20*/ entry_blank,
		/*21*/ entry_blank,
		/*22*/ entry_blank,
		/*23*/ entry_blank,
		/*24*/ entry_blank,
		/*25*/ entry_blank,
		/*26*/ entry_blank,
		/*27*/ entry_blank,
		/*28*/ entry_blank,
		/*29*/ entry_blank,
		/*2A*/ entry_blank,
		/*2B*/ entry_blank,
		/*2C*/ entry_blank,
		/*2D*/ entry_blank,
		/*2E*/ entry_blank,
		/*2F*/ entry_blank,
		/*30*/ entry_blank,
		/*31*/ entry_blank,
		/*32*/ entry_blank,
		/*33*/ entry_blank,
		/*34*/ entry_blank,
		/*35*/ entry_blank,
		/*36*/ entry_blank,
		/*37*/ entry_blank,
		/*38*/ entry_blank,
		/*39*/ entry_blank,
		/*3A*/ entry_blank,
		/*3B*/ entry_blank,
		/*3C*/ entry_blank,
		/*3D*/ entry_blank,
		/*3E*/ entry_blank,
		/*3F*/ entry_blank,
		/*40*/ entry_blank,
		/*41*/ entry_blank,
		/*42*/ entry_blank,
		/*43*/ entry_blank,
		/*44*/ entry_blank,
		/*45*/ entry_blank,
		/*46*/ entry_blank,
		/*47*/ entry_blank,
		/*48*/ entry_blank,
		/*49*/ entry_blank,
		/*4A*/ entry_blank,
		/*4B*/ entry_blank,
		/*4C*/ entry_blank,
		/*4D*/ entry_blank,
		/*4E*/ entry_blank,
		/*4F*/ entry_blank,
		/*50*/ entry_blank,
		/*51*/ entry_blank,
		/*52*/ entry_blank,
		/*53*/ entry_blank,
		/*54*/ entry_blank,
		/*55*/ entry_blank,
		/*56*/ entry_blank,
		/*57*/ entry_blank,
		/*58*/ entry_blank,
		/*59*/ entry_blank,
		/*5A*/ entry_blank,
		/*5B*/ entry_blank,
		/*5C*/ entry_blank,
		/*5D*/ entry_blank,
		/*5E*/ entry_blank,
		/*5F*/ entry_blank,
		/*60*/ entry_blank,
		/*61*/ entry_blank,
		/*62*/ entry_blank,
		/*63*/ entry_blank,
		/*64*/ entry_blank,
		/*65*/ entry_blank,
		/*66*/ entry_blank,
		/*67*/ entry_blank,
		/*68*/ entry_blank,
		/*69*/ entry_blank,
		/*6A*/ entry_blank,
		/*6B*/ entry_blank,
		/*6C*/ entry_blank,
		/*6D*/ entry_blank,
		/*6E*/ entry_blank,
		/*6F*/ entry_blank,
		/*70*/ entry_blank,
		/*71*/ entry_blank,
		/*72*/ entry_blank,
		/*73*/ entry_blank,
		/*74*/ entry_blank,
		/*75*/ entry_blank,
		/*76*/ entry_blank,
		/*77*/ entry_blank,
		/*78*/ entry_blank,
		/*79*/ entry_blank,
		/*7A*/ entry_blank,
		/*7B*/ entry_blank,
		/*7C*/ entry_blank,
		/*7D*/ entry_blank,
		/*7E*/ entry_blank,
		/*7F*/ entry_blank,
		/*80*/ entry_blank,
		/*81*/ entry_blank,
		/*82*/ entry_blank,
		/*83*/ entry_blank,
		/*84*/ entry_blank,
		/*85*/ entry_blank,
		/*86*/ entry_blank,
		/*87*/ entry_blank,

		/*88*/ entry_blank,
		/*89*/ entry_blank,
		/*8A*/ entry_2(0x8A, ops::PFNACC, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*8B*/ entry_blank,
		/*8C*/ entry_blank,
		/*8D*/ entry_blank,
		/*8E*/ entry_2(0x8E, ops::PFPNACC, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*8F*/ entry_blank,

		/*90*/ entry_2(0x90, ops::PFCMPGE, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*91*/ entry_blank,
		/*92*/ entry_blank,
		/*93*/ entry_blank,
		/*94*/ entry_2(0x94, ops::PFMIN, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*95*/ entry_blank,
		/*96*/ entry_2(0x96, ops::PFRCP, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*97*/ entry_2(0x97, ops::PFRSQRT, OpKind::RegMmx, OpKind::RegMmxMem64),

		/*98*/ entry_blank,
		/*99*/ entry_blank,
		/*9A*/ entry_2(0x9A, ops::PFSUB, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*9B*/ entry_blank,
		/*9C*/ entry_blank,
		/*9D*/ entry_blank,
		/*9E*/ entry_2(0x9E, ops::PFADD, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*9F*/ entry_blank,

		/*A0*/ entry_2(0xA0, ops::PFCMPGT, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*A1*/ entry_blank,
		/*A2*/ entry_blank,
		/*A3*/ entry_blank,
		/*A4*/ entry_2(0xA4, ops::PFMAX, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*A5*/ entry_blank,
		/*A6*/ entry_2(0xA6, ops::PFRCPIT1, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*A7*/ entry_2(0xA7, ops::PFRSQIT1, OpKind::RegMmx, OpKind::RegMmxMem64),

		/*A8*/ entry_blank,
		/*A9*/ entry_blank,
		/*AA*/ entry_2(0xAA, ops::PFSUBR, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*AB*/ entry_blank,
		/*AC*/ entry_blank,
		/*AD*/ entry_blank,
		/*AE*/ entry_2(0xAE, ops::PFACC, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*AF*/ entry_blank,

		/*B0*/ entry_2(0xB0, ops::PFCMPEQ, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*B1*/ entry_blank,
		/*B2*/ entry_blank,
		/*B3*/ entry_blank,
		/*B4*/ entry_2(0xB4, ops::PFMUL, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*B5*/ entry_blank,
		/*B6*/ entry_2(0xB6, ops::PFRCPIT2, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*B7*/ entry_2(0xB7, ops::PMULHRW, OpKind::RegMmx, OpKind::RegMmxMem64),

		/*B8*/ entry_blank,
		/*B9*/ entry_blank,
		/*BA*/ entry_blank,
		/*BB*/ entry_2(0xBB, ops::PSWAPD, OpKind::RegMmx, OpKind::RegMmxMem64),
		/*BC*/ entry_blank,
		/*BD*/ entry_blank,
		/*BE*/ entry_blank,
		/*BF*/ entry_2(0xBF, ops::PAVGUSB, OpKind::RegMmx, OpKind::RegMmxMem64),

		/*C0*/ entry_blank,
		/*C1*/ entry_blank,
		/*C2*/ entry_blank,
		/*C3*/ entry_blank,
		/*C4*/ entry_blank,
		/*C5*/ entry_blank,
		/*C6*/ entry_blank,
		/*C7*/ entry_blank,
		/*C8*/ entry_blank,
		/*C9*/ entry_blank,
		/*CA*/ entry_blank,
		/*CB*/ entry_blank,
		/*CC*/ entry_blank,
		/*CD*/ entry_blank,
		/*CE*/ entry_blank,
		/*CF*/ entry_blank,
		/*D0*/ entry_blank,
		/*D1*/ entry_blank,
		/*D2*/ entry_blank,
		/*D3*/ entry_blank,
		/*D4*/ entry_blank,
		/*D5*/ entry_blank,
		/*D6*/ entry_blank,
		/*D7*/ entry_blank,
		/*D8*/ entry_blank,
		/*D9*/ entry_blank,
		/*DA*/ entry_blank,
		/*DB*/ entry_blank,
		/*DC*/ entry_blank,
		/*DD*/ entry_blank,
		/*DE*/ entry_blank,
		/*DF*/ entry_blank,
		/*E0*/ entry_blank,
		/*E1*/ entry_blank,
		/*E2*/ entry_blank,
		/*E3*/ entry_blank,
		/*E4*/ entry_blank,
		/*E5*/ entry_blank,
		/*E6*/ entry_blank,
		/*E7*/ entry_blank,
		/*E8*/ entry_blank,
		/*E9*/ entry_blank,
		/*EA*/ entry_blank,
		/*EB*/ entry_blank,
		/*EC*/ entry_blank,
		/*ED*/ entry_blank,
		/*EE*/ entry_blank,
		/*EF*/ entry_blank,
		/*F0*/ entry_blank,
		/*F1*/ entry_blank,
		/*F2*/ entry_blank,
		/*F3*/ entry_blank,
		/*F4*/ entry_blank,
		/*F5*/ entry_blank,
		/*F6*/ entry_blank,
		/*F7*/ entry_blank,
		/*F8*/ entry_blank,
		/*F9*/ entry_blank,
		/*FA*/ entry_blank,
		/*FB*/ entry_blank,
		/*FC*/ entry_blank,
		/*FD*/ entry_blank,
		/*FE*/ entry_blank,
		/*FF*/ entry_blank,
	};
}
